# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhlisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songg_title',
            new_name='song_title',
        ),
    ]
